### PR TITLE
Upstream merge + BTG changes and testnet servers 

### PR DESCRIPTION
**Pull request by wilsonmeier**
Also started renaming images and build artifacts

### CODE REVIEW

**Comment by h4x3rotab** [comment]
Let's not use "Electrum Gold". There's already a well known scam site using this name. Maybe "Electrum BTG" or "Electrum for Bitcoin Gold" is better?

**Comment by h4x3rotab** [comment]
lgtm otherwise

**Comment by h4x3rotab** [comment]
Another EPIC pull request 🕶

**Comment by wilsonmeier** [comment]
Another EPIC review :+1:

**Pull request merged**
